### ISSUE TITLE
LLM-X in docker not connecting to Ollama in docker container

### ISSUE THREAD

**Issue by neuhaus** [mrdjohnson/llm-x#32]
I'm running docker and LLM-X in a container with the following compose.yml file:

```
version: '3.8'

services:
  ollama:
    image: ollama/ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    container_name: ollama
    networks:
      - ollama_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]  # enables GPU usage
    volumes:
      - /usr/share/ollama/.ollama:/root/.ollama  # persistent storage for data
    ports:
      - "127.0.0.1:11434:11434"  # expose the port to the host
    restart: unless-stopped

  llmx:
    container_name: llmx
    build: .
    networks:
      - ollama_network
    ports:
      - "5173:5173"

networks:
  ollama_network:
    driver: bridge
    name: ollama_network
```

In the LLM-X configuration i add ollama and then configure it to be at http://ollama:11434/ but it doesn't show me any models (there are quite a few it should show).

I added a test container with the same network and i can connect from the test container to ollama on port 11434 without any problems so i think it's an issue with LLM-X.

Has anyone gotten this setup to work (Docker containers for ollama + llm-x)?
